language: python
python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install mypy
  - pip3 install flake8
  - pip3 install nose

script:
  - python3 -m mypy --config-file=mypy.ini p2p_python tests
  - flake8 p2p_python --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  - flake8 p2p_python --count --exit-zero --extend-ignore=F403,F405 --max-complexity=12 --max-line-length=120 --statistics
  - python3 -m nose -v tests/base.py
  - python3 -m nose -v tests/advance.py
  - python3 -m nose -v tests/options.py
